[{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 134,
  majorCode: '140109',
  professionName: '文科试验班类',
  professionCode: '1',
  remarks: null,
  maxScore: 0,
  minScore: '662',
  avgScore: 0,
  lowSort: '8',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 115,
  majorCode: '140109',
  professionName:
            '文科试验班类(含中国语言文学类、考古学、历史学类、哲学类、社会学类、国际政治、法学、信息管理与信息系统、新闻传播学类等专业，详见招生章程)',
  professionCode: '1',
  remarks: null,
  maxScore: 0,
  minScore: '676',
  avgScore: 0,
  lowSort: '7',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '140109',
  professionName: '文科试验班类(包含专业见院校招生章程)',
  professionCode: '1',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '140102',
  professionName: '人文科学试验班(艺术史论、戏剧与影视学类、艺术学理论类(文化产业))',
  professionCode: '2',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 130,
  majorCode: '140102',
  professionName: '人文科学试验班',
  professionCode: '3',
  remarks: null,
  maxScore: 0,
  minScore: '658',
  avgScore: 0,
  lowSort: '18',
  maxSort: 0,
  enterNum: '2',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '0101',
  professionName: '哲学类(哲学、宗教学、逻辑学(科技哲学))',
  professionCode: '5',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 112,
  majorCode: '140102',
  professionName: '人文科学试验班(含艺术史论、戏剧与影视学类、艺术学理论类(文化产业))',
  professionCode: '6',
  remarks: null,
  maxScore: 0,
  minScore: '673',
  avgScore: 0,
  lowSort: '15',
  maxSort: 0,
  enterNum: '2',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '0201',
  professionName: '经济学类(经济学、金融学、国际经济与贸易、保险学、财政学资源与环境经济学)',
  professionCode: '6',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '030101',
  professionName: '法学',
  professionCode: '7',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '030202',
  professionName: '国际政治(国政、外交学、国际政经)',
  professionCode: '8',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 130,
  majorCode: '0101',
  professionName: '哲学类',
  professionCode: '9',
  remarks: null,
  maxScore: 0,
  minScore: '658',
  avgScore: 0,
  lowSort: '18',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '0303',
  professionName: '社会学类(社会学、社会工作、人类学)',
  professionCode: '9',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '0501',
  professionName: '中国语言文学类(汉语言文学汉语言、古典文献学、应用语言学)',
  professionCode: '1',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 132,
  majorCode: '0201',
  professionName: '经济学类',
  professionCode: '11',
  remarks: null,
  maxScore: 0,
  minScore: '660',
  avgScore: 0,
  lowSort: '15',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '050201',
  professionName: '英语(外语语种英语；需口试)',
  professionCode: '11',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 136,
  majorCode: '030101',
  professionName: '法学',
  professionCode: '12',
  remarks: null,
  maxScore: 0,
  minScore: '664',
  avgScore: 0,
  lowSort: '5',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 134,
  majorCode: '030202',
  professionName: '国际政治',
  professionCode: '14',
  remarks: null,
  maxScore: 0,
  minScore: '662',
  avgScore: 0,
  lowSort: '8',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 130,
  majorCode: '030301',
  professionName: '社会学',
  professionCode: '15',
  remarks: null,
  maxScore: 0,
  minScore: '658',
  avgScore: 0,
  lowSort: '18',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '0503',
  professionName: '新闻传播学类(新闻学、广播电视学、广告学、编辑出版学)',
  professionCode: '15',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '0601',
  professionName: '历史学类(历史学(中国史)世界史、外国语言与外国历史)',
  professionCode: '16',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 133,
  majorCode: '0501',
  professionName: '中国语言文学类',
  professionCode: '17',
  remarks: null,
  maxScore: 0,
  minScore: '661',
  avgScore: 0,
  lowSort: '13',
  maxSort: 0,
  enterNum: '2',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '060103',
  professionName: '考古学',
  professionCode: '17',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 130,
  majorCode: '050201',
  professionName: '英语',
  professionCode: '19',
  remarks: null,
  maxScore: 0,
  minScore: '658',
  avgScore: 0,
  lowSort: '18',
  maxSort: 0,
  enterNum: '2',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 111,
  majorCode: '0101',
  professionName: '哲学类(含哲学、宗教学、逻辑学(科技哲学))',
  professionCode: '2',
  remarks: null,
  maxScore: 0,
  minScore: '672',
  avgScore: 0,
  lowSort: '21',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 133,
  majorCode: '0503',
  professionName: '新闻传播学类',
  professionCode: '23',
  remarks: null,
  maxScore: 0,
  minScore: '661',
  avgScore: 0,
  lowSort: '13',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 130,
  majorCode: '0601',
  professionName: '历史学类',
  professionCode: '24',
  remarks: null,
  maxScore: 0,
  minScore: '658',
  avgScore: 0,
  lowSort: '18',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 113,
  majorCode: '0201',
  professionName: '经济学类(含经济学、金融学、国际经济与贸易、保险学(风险管理与保险)、财政学、资源与环境经济学)',
  professionCode: '25',
  remarks: null,
  maxScore: 0,
  minScore: '674',
  avgScore: 0,
  lowSort: '11',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 116,
  majorCode: '030101',
  professionName: '法学',
  professionCode: '28',
  remarks: null,
  maxScore: 0,
  minScore: '677',
  avgScore: 0,
  lowSort: '8',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '120102',
  professionName: '信息管理与信息系统',
  professionCode: '3',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '1202',
  professionName: '工商管理类(金融学、经济学(金融)、会计学、市场营销)',
  professionCode: '31',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 112,
  majorCode: '030202',
  professionName: '国际政治(招考方向：国政、外交学、国际政经)',
  professionCode: '32',
  remarks: null,
  maxScore: 0,
  minScore: '673',
  avgScore: 0,
  lowSort: '15',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2019,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: -542,
  majorCode: '1204',
  professionName: '公共管理类(政治学与行政学、城市管理、行政管理)',
  professionCode: '32',
  remarks: null,
  maxScore: 0,
  minScore: 0,
  avgScore: 0,
  lowSort: 0,
  maxSort: 0,
  enterNum: 0,
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 111,
  majorCode: '0303',
  professionName: '社会学类(含社会学、社会工作)',
  professionCode: '36',
  remarks: null,
  maxScore: 0,
  minScore: '672',
  avgScore: 0,
  lowSort: '21',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 112,
  majorCode: '0501',
  professionName: '中国语言文学类(含汉语言文学、汉语言、古典文献学、应用语言学)',
  professionCode: '4',
  remarks: null,
  maxScore: 0,
  minScore: '673',
  avgScore: 0,
  lowSort: '15',
  maxSort: 0,
  enterNum: '2',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 111,
  majorCode: '050201',
  professionName: '英语',
  professionCode: '45',
  remarks: null,
  maxScore: 0,
  minScore: '672',
  avgScore: 0,
  lowSort: '21',
  maxSort: 0,
  enterNum: '2',
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 145,
  majorCode: '1202',
  professionName: '工商管理类',
  professionCode: '48',
  remarks: null,
  maxScore: 0,
  minScore: '673',
  avgScore: 0,
  lowSort: '2',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2017,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 131,
  majorCode: '1204',
  professionName: '公共管理类',
  professionCode: '49',
  remarks: null,
  maxScore: 0,
  minScore: '659',
  avgScore: 0,
  lowSort: '17',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 115,
  majorCode: '0503',
  professionName: '新闻传播学类(含新闻学、广播电视学、广告学、编辑出版学)',
  professionCode: '51',
  remarks: null,
  maxScore: 0,
  minScore: '676',
  avgScore: 0,
  lowSort: '7',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 113,
  majorCode: '0601',
  professionName: '历史学类(含历史学(中国史)、世界史、外国语言与外国历史)',
  professionCode: '54',
  remarks: null,
  maxScore: 0,
  minScore: '674',
  avgScore: 0,
  lowSort: '11',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 125,
  majorCode: '1202',
  professionName: '工商管理类(含金融学、经济学(金融)、会计学、市场营销)',
  professionCode: 'C8',
  remarks: null,
  maxScore: 0,
  minScore: '686',
  avgScore: 0,
  lowSort: '3',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
},
{
  year: 2018,
  courseType: 1,
  batch: 1,
  batchName: '本一批',
  uCode: '42_838_0_0',
  chooseLevel: '',
  lineDiff: 111,
  majorCode: '1204',
  professionName: '公共管理类(含政治学与行政学、城市管理、行政管理)',
  professionCode: 'D1',
  remarks: null,
  maxScore: 0,
  minScore: '672',
  avgScore: 0,
  lowSort: '21',
  maxSort: 0,
  enterNum: '1',
  countOfZJZY: 0,
}];
